## 2.2 Tensors

pp. 28 ~

In [5]:
import torch
import numpy as np

In [6]:
# 1D tensor created by using torch
torch_array = torch.tensor([0,1,2,3])
torch_array

tensor([0, 1, 2, 3])

In [7]:
# 1D array created by numpy
np_array = np.array([0,1,2,3])
np_array

array([0, 1, 2, 3])

In [8]:
# It is possible to transform numpy array into tensor 

torch_array = torch.from_numpy(np_array)
torch_array

tensor([0, 1, 2, 3])

In [9]:
# Also, it's possible to go back

torch2np_array = torch_array.numpy()
torch2np_array

array([0, 1, 2, 3])

In [10]:
# 2D tensor

np_array = np.array([[0,1,2],[3,4,5]])
torch_array = torch.from_numpy(np_array)
torch2np_array = torch_array.numpy()

In [11]:
torch_array

tensor([[0, 1, 2],
        [3, 4, 5]])

In [12]:
torch2np_array

array([[0, 1, 2],
       [3, 4, 5]])

### Various tensors

pp. 30

In [13]:
torch_array = torch.arange(10)
torch_array

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
torch_array = torch.linspace(0,1,6) # from 0 to 1, create 6 ea.
torch_array

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000])

In [15]:
torch_array = torch.ones((3,3))
torch_array

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch_array = torch.zeros((2,2))
torch_array

tensor([[0., 0.],
        [0., 0.]])

In [17]:
# Generate an array of random numbers that follows normal distribution
torch_array = torch.randn(4)
torch_array

tensor([-0.3879, -1.4916,  0.1306,  0.8606])

### Tensor manipulation

In [18]:
torch_array = torch.arange(10)
print(torch_array)
torch_array = torch_array.view(5,2) # transform the tensor into 5x2
print(torch_array)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [19]:
# torch.transpose(input, dim0, dim1)
torch_array = torch_array.transpose(0,1)

In [20]:
torch_array

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

In [24]:
torch_array = torch.arange(10)
torch_array[2]

tensor(2)

In [26]:
torch_array = torch.arange(10)
torch_array[2:5]

tensor([2, 3, 4])

In [27]:
# addition - elementwise
x1 = torch.arange(4)
print(x1)
x2 = torch.add(x1,4)
print(x2)

tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])


In [28]:
# multiplication - elementwise
x3 = torch.arange(4)
print(x3)
x4 = torch.mul(x1,4)
print(x4)

tensor([0, 1, 2, 3])
tensor([ 0,  4,  8, 12])


In [33]:
# vector multiplication (inner product)
x1 = torch.arange(4)
x2 = torch.arange(4)
print(torch.matmul(x1,x2))
print(torch.dot(x1,x2))

tensor(14)
tensor(14)


In [35]:
# vector and matrix multiplication 
X1 = torch.arange(8).view(2,4)
x2 = torch.arange(4)
print(torch.matmul(X1,x2))
print(torch.mv(X1,x2))

tensor([14, 38])
tensor([14, 38])


In [36]:
# matrix and matrix multiplication 
X1 = torch.arange(8).view(2,4)
X2 = torch.arange(8).view(2,4).t()
print(torch.matmul(X1,X2))
print(torch.mm(X1,X2))

tensor([[ 14,  38],
        [ 38, 126]])
tensor([[ 14,  38],
        [ 38, 126]])


In [ ]:
# multiplication between batches
