### Build Basic GAN

#### Intro to pytorch

torch.nn refers to the Pytorch neural network module, where many powerful classes are stored.

In [1]:
import torch
from torch import nn

In [3]:
# nn.Linear

linear = nn.Linear(10,2)  # initialize linear object, which takes nx10 matrix and returns nx2 matrix
example_input = torch.randn(3,10)
example_output = linear(example_input)
example_output

tensor([[ 1.5436, -0.9178],
        [ 0.1889, -0.0929],
        [-0.0234,  0.0684]], grad_fn=<AddmmBackward>)

In [4]:
example_input.shape

torch.Size([3, 10])

In [5]:
example_output.shape

torch.Size([3, 2])

In [6]:
linear

Linear(in_features=10, out_features=2, bias=True)

In [7]:
# nn.ReLU

relu = nn.ReLU()
relu_output = relu(example_output)
relu_output

tensor([[1.5436, 0.0000],
        [0.1889, 0.0000],
        [0.0000, 0.0684]], grad_fn=<ReluBackward0>)

In [8]:
# nn.BatchNorm1d

batch_norm = nn.BatchNorm1d(2) # argument is the no. of input dimension
batchnorm_output = batch_norm(relu_output)
batchnorm_output

tensor([[ 1.4053, -0.7037],
        [-0.5653, -0.7037],
        [-0.8400,  1.4075]], grad_fn=<NativeBatchNormBackward>)

In [9]:
# nn.Sequential

mlp_layer = nn.Sequential(
    nn.Linear(5,2),
    nn.BatchNorm1d(2),
    nn.ReLU()
)

test_example = torch.randn(5,5)+1
print("input: ")
print(test_example)
print("output: ")
print(mlp_layer(test_example))

input: 
tensor([[ 8.0790e-01,  9.3900e-01,  3.2595e-01,  4.3299e-01,  2.8457e+00],
        [ 1.4852e+00,  2.1299e+00,  3.4956e-01,  2.0044e+00,  2.3568e+00],
        [ 2.2700e+00,  1.1915e+00,  1.7092e+00,  2.4570e+00,  1.6445e+00],
        [ 9.9105e-01, -3.5830e-01,  4.1790e-01,  1.6565e+00, -1.2743e-04],
        [ 1.0763e+00,  1.9365e+00,  2.4753e+00,  2.1826e+00, -2.2777e-01]])
output: 
tensor([[1.6756, 0.0195],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.5336, 1.8475],
        [0.0000, 0.0000]], grad_fn=<ReluBackward0>)


In [ ]:
# Optimization